name_tags: dict[str, str | tuple] = {
    # Target Type Value 70:
    # Movie
    "collection": "TITLE",
    "collection_imdb": "IMDB",
    "collection_tmdb": "TMDB",
    "movies_number": "TOTAL_PARTS",
    # TV Series
    "series": "TITLE",
    "series_imdb": "IMDB",
    "series_tmdb": "TMDB",
    "series_tvdb": "TVDB",
    "seasons_number": "TOTAL_PARTS",
    # Target Type Value 60:
    # TV Series
    "season": "TITLE",
    "season_number": "PART_NUMBER",
    "episodes_season_number": "TOTAL_PARTS",
    # Target Type Value 50:
    # Movie
    "movie_number": "PART_NUMBER",
    "movie_imdb": "IMDB",
    "movie_tmdb": "TMDB",
    "movie_tvdb": "TVDB",
    # TV Series
    "episode_number": "PART_NUMBER",
    "episode_imdb": "IMDB",
    "episode_tmdb": "TMDB",
    "episode_tvdb": "TVDB",
    # Common
    "title": "TITLE",
    "directors": "DIRECTOR",
    "directors_assistant": "ASSISTANT_DIRECTOR",
    "directors_photography": "DIRECTOR_OF_PHOTOGRAPHY",
    "designers_production": "PRODUCTION_DESIGNER",
    "designers_costume": "COSTUME_DESIGNER",
    "actors_characters": ("ACTOR", "CHARACTER"),
    "writers": "WRITTEN_BY",
    "screenplayers": "SCREENPLAY_BY",
    "editors": "EDITOR",
    "producers": "PRODUCER",
    "coproducers": "COPRODUCER",
    "producers_executives": "EXECUTIVE_PRODUCER",
    "distributors": "DISTRIBUTED_BY",
    "mastering_engineers": "MASTERED_BY",
    "productions_studio": "PRODUCTION_STUDIO",
    "publishers": "PUBLISHER",
    "locations_recording": "RECORDING_LOCATION",
    "genres": "GENRE",
    "keywords": "KEYWORDS",
    "moods": "MOOD",
    "rating": "RATING",
    "content_type": "CONTENT_TYPE",
    "subject": "SUBJECT",
    "description": "DESCRIPTION",
    "synopsis": "SYNOPSIS",
    "summary": "SUMMARY",
    "comment": "COMMENT",
    "date_written": "DATE_WRITTEN",
    "date_released": "DATE_RELEASED",
}

unique_value_tags: set[str] = {
    "collection_imdb",
    "collection_tmdb",
    "series_imdb",
    "series_tmdb",
    "series_tvdb",
    "movie_imdb",
    "movie_tmdb",
    "movie_tvdb",
    "episode_imdb",
    "episode_tmdb",
    "episode_tvdb",
    "collection",
    "series",
    "season",
    "title",
    "movies_number",
    "seasons_number",
    "season_number",
    "episodes_season_number",
    "movie_number",
    "episode_number",
    "date_written",
    "date_released",
    "rating",
    "content_type",
    "subject",
}
